//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sql_project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Examination_System_Final_ProjectEntities2 : DbContext
    {
        public Examination_System_Final_ProjectEntities2()
            : base("name=Examination_System_Final_ProjectEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Choice> Choices { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Exam> Exams { get; set; }
        public virtual DbSet<Inst_Course> Inst_Course { get; set; }
        public virtual DbSet<Instructor> Instructors { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Std_Course> Std_Course { get; set; }
        public virtual DbSet<Std_Ques_Exam> Std_Ques_Exam { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
    
        [DbFunction("Examination_System_Final_ProjectEntities2", "Get_Random_Questions")]
        public virtual IQueryable<Get_Random_Questions_Result> Get_Random_Questions(string type, Nullable<int> crs_ID)
        {
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var crs_IDParameter = crs_ID.HasValue ?
                new ObjectParameter("Crs_ID", crs_ID) :
                new ObjectParameter("Crs_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Get_Random_Questions_Result>("[Examination_System_Final_ProjectEntities2].[Get_Random_Questions](@Type, @Crs_ID)", typeParameter, crs_IDParameter);
        }
    
        public virtual ObjectResult<string> Crs_Topics(Nullable<int> crs_ID)
        {
            var crs_IDParameter = crs_ID.HasValue ?
                new ObjectParameter("Crs_ID", crs_ID) :
                new ObjectParameter("Crs_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Crs_Topics", crs_IDParameter);
        }
    
        public virtual ObjectResult<Exam_answer_Result> Exam_answer(Nullable<int> exam_No, string first_name, string last_name, Nullable<int> ques_No, string stu_answer)
        {
            var exam_NoParameter = exam_No.HasValue ?
                new ObjectParameter("Exam_No", exam_No) :
                new ObjectParameter("Exam_No", typeof(int));
    
            var first_nameParameter = first_name != null ?
                new ObjectParameter("First_name", first_name) :
                new ObjectParameter("First_name", typeof(string));
    
            var last_nameParameter = last_name != null ?
                new ObjectParameter("Last_name", last_name) :
                new ObjectParameter("Last_name", typeof(string));
    
            var ques_NoParameter = ques_No.HasValue ?
                new ObjectParameter("Ques_No", ques_No) :
                new ObjectParameter("Ques_No", typeof(int));
    
            var stu_answerParameter = stu_answer != null ?
                new ObjectParameter("Stu_answer", stu_answer) :
                new ObjectParameter("Stu_answer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Exam_answer_Result>("Exam_answer", exam_NoParameter, first_nameParameter, last_nameParameter, ques_NoParameter, stu_answerParameter);
        }
    
        public virtual int Exam_correction(Nullable<int> exam_No, Nullable<int> std_ID)
        {
            var exam_NoParameter = exam_No.HasValue ?
                new ObjectParameter("Exam_No", exam_No) :
                new ObjectParameter("Exam_No", typeof(int));
    
            var std_IDParameter = std_ID.HasValue ?
                new ObjectParameter("Std_ID", std_ID) :
                new ObjectParameter("Std_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Exam_correction", exam_NoParameter, std_IDParameter);
        }
    
        public virtual ObjectResult<Exam_Generation_Result> Exam_Generation(string crs_Name, Nullable<int> st_id, Nullable<int> mCQ_No, Nullable<int> tF_No)
        {
            var crs_NameParameter = crs_Name != null ?
                new ObjectParameter("Crs_Name", crs_Name) :
                new ObjectParameter("Crs_Name", typeof(string));
    
            var st_idParameter = st_id.HasValue ?
                new ObjectParameter("st_id", st_id) :
                new ObjectParameter("st_id", typeof(int));
    
            var mCQ_NoParameter = mCQ_No.HasValue ?
                new ObjectParameter("MCQ_No", mCQ_No) :
                new ObjectParameter("MCQ_No", typeof(int));
    
            var tF_NoParameter = tF_No.HasValue ?
                new ObjectParameter("TF_No", tF_No) :
                new ObjectParameter("TF_No", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Exam_Generation_Result>("Exam_Generation", crs_NameParameter, st_idParameter, mCQ_NoParameter, tF_NoParameter);
        }
    
        public virtual ObjectResult<Exam_Ques_Choices_Result> Exam_Ques_Choices(Nullable<int> exam_Num)
        {
            var exam_NumParameter = exam_Num.HasValue ?
                new ObjectParameter("Exam_Num", exam_Num) :
                new ObjectParameter("Exam_Num", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Exam_Ques_Choices_Result>("Exam_Ques_Choices", exam_NumParameter);
        }
    
        public virtual ObjectResult<string> Get_Std_Answers(Nullable<int> exam_ID, Nullable<int> st_ID, string ans1, string ans2, string ans3, string ans4, string ans5, string ans6, string ans7, string ans8, string ans9, string ans10)
        {
            var exam_IDParameter = exam_ID.HasValue ?
                new ObjectParameter("Exam_ID", exam_ID) :
                new ObjectParameter("Exam_ID", typeof(int));
    
            var st_IDParameter = st_ID.HasValue ?
                new ObjectParameter("St_ID", st_ID) :
                new ObjectParameter("St_ID", typeof(int));
    
            var ans1Parameter = ans1 != null ?
                new ObjectParameter("ans1", ans1) :
                new ObjectParameter("ans1", typeof(string));
    
            var ans2Parameter = ans2 != null ?
                new ObjectParameter("ans2", ans2) :
                new ObjectParameter("ans2", typeof(string));
    
            var ans3Parameter = ans3 != null ?
                new ObjectParameter("ans3", ans3) :
                new ObjectParameter("ans3", typeof(string));
    
            var ans4Parameter = ans4 != null ?
                new ObjectParameter("ans4", ans4) :
                new ObjectParameter("ans4", typeof(string));
    
            var ans5Parameter = ans5 != null ?
                new ObjectParameter("ans5", ans5) :
                new ObjectParameter("ans5", typeof(string));
    
            var ans6Parameter = ans6 != null ?
                new ObjectParameter("ans6", ans6) :
                new ObjectParameter("ans6", typeof(string));
    
            var ans7Parameter = ans7 != null ?
                new ObjectParameter("ans7", ans7) :
                new ObjectParameter("ans7", typeof(string));
    
            var ans8Parameter = ans8 != null ?
                new ObjectParameter("ans8", ans8) :
                new ObjectParameter("ans8", typeof(string));
    
            var ans9Parameter = ans9 != null ?
                new ObjectParameter("ans9", ans9) :
                new ObjectParameter("ans9", typeof(string));
    
            var ans10Parameter = ans10 != null ?
                new ObjectParameter("ans10", ans10) :
                new ObjectParameter("ans10", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Get_Std_Answers", exam_IDParameter, st_IDParameter, ans1Parameter, ans2Parameter, ans3Parameter, ans4Parameter, ans5Parameter, ans6Parameter, ans7Parameter, ans8Parameter, ans9Parameter, ans10Parameter);
        }
    
        public virtual ObjectResult<Ins_Crs_Result> Ins_Crs(Nullable<int> ins_ID)
        {
            var ins_IDParameter = ins_ID.HasValue ?
                new ObjectParameter("Ins_ID", ins_ID) :
                new ObjectParameter("Ins_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ins_Crs_Result>("Ins_Crs", ins_IDParameter);
        }
    
        public virtual ObjectResult<string> InsertIns_Course(Nullable<int> insId, Nullable<int> courseId)
        {
            var insIdParameter = insId.HasValue ?
                new ObjectParameter("insId", insId) :
                new ObjectParameter("insId", typeof(int));
    
            var courseIdParameter = courseId.HasValue ?
                new ObjectParameter("courseId", courseId) :
                new ObjectParameter("courseId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("InsertIns_Course", insIdParameter, courseIdParameter);
        }
    
        public virtual ObjectResult<string> InsertSt_Course(Nullable<int> stId, Nullable<int> courseId, Nullable<int> g)
        {
            var stIdParameter = stId.HasValue ?
                new ObjectParameter("stId", stId) :
                new ObjectParameter("stId", typeof(int));
    
            var courseIdParameter = courseId.HasValue ?
                new ObjectParameter("courseId", courseId) :
                new ObjectParameter("courseId", typeof(int));
    
            var gParameter = g.HasValue ?
                new ObjectParameter("G", g) :
                new ObjectParameter("G", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("InsertSt_Course", stIdParameter, courseIdParameter, gParameter);
        }
    
        public virtual ObjectResult<Ques_StdAnswer_Result> Ques_StdAnswer(Nullable<int> exam_Num, Nullable<int> std_ID)
        {
            var exam_NumParameter = exam_Num.HasValue ?
                new ObjectParameter("Exam_Num", exam_Num) :
                new ObjectParameter("Exam_Num", typeof(int));
    
            var std_IDParameter = std_ID.HasValue ?
                new ObjectParameter("Std_ID", std_ID) :
                new ObjectParameter("Std_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ques_StdAnswer_Result>("Ques_StdAnswer", exam_NumParameter, std_IDParameter);
        }
    
        public virtual ObjectResult<selectCourse_Ins_Result> selectCourse_Ins(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectCourse_Ins_Result>("selectCourse_Ins", idParameter);
        }
    
        public virtual ObjectResult<selectIns_Course_Result> selectIns_Course(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectIns_Course_Result>("selectIns_Course", idParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<Std_Dept_Result> Std_Dept(Nullable<int> dep_ID)
        {
            var dep_IDParameter = dep_ID.HasValue ?
                new ObjectParameter("Dep_ID", dep_ID) :
                new ObjectParameter("Dep_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Std_Dept_Result>("Std_Dept", dep_IDParameter);
        }
    
        public virtual ObjectResult<Std_Garde_Result> Std_Garde(Nullable<int> std_ID)
        {
            var std_IDParameter = std_ID.HasValue ?
                new ObjectParameter("Std_ID", std_ID) :
                new ObjectParameter("Std_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Std_Garde_Result>("Std_Garde", std_IDParameter);
        }
    
        public virtual ObjectResult<StGrade_Course_Result> StGrade_Course(Nullable<int> stID, Nullable<int> courseID)
        {
            var stIDParameter = stID.HasValue ?
                new ObjectParameter("StID", stID) :
                new ObjectParameter("StID", typeof(int));
    
            var courseIDParameter = courseID.HasValue ?
                new ObjectParameter("CourseID", courseID) :
                new ObjectParameter("CourseID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StGrade_Course_Result>("StGrade_Course", stIDParameter, courseIDParameter);
        }
    
        public virtual ObjectResult<StudAnswer_Result> StudAnswer(Nullable<int> stID, Nullable<int> questID, Nullable<int> examID)
        {
            var stIDParameter = stID.HasValue ?
                new ObjectParameter("stID", stID) :
                new ObjectParameter("stID", typeof(int));
    
            var questIDParameter = questID.HasValue ?
                new ObjectParameter("questID", questID) :
                new ObjectParameter("questID", typeof(int));
    
            var examIDParameter = examID.HasValue ?
                new ObjectParameter("examID", examID) :
                new ObjectParameter("examID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StudAnswer_Result>("StudAnswer", stIDParameter, questIDParameter, examIDParameter);
        }
    
        public virtual ObjectResult<string> Student_Answer(Nullable<int> exam_No, Nullable<int> std_ID, string ans1, string ans2, string ans3, string ans4, string ans5, string ans6, string ans7, string ans8, string ans9, string ans10)
        {
            var exam_NoParameter = exam_No.HasValue ?
                new ObjectParameter("Exam_No", exam_No) :
                new ObjectParameter("Exam_No", typeof(int));
    
            var std_IDParameter = std_ID.HasValue ?
                new ObjectParameter("Std_ID", std_ID) :
                new ObjectParameter("Std_ID", typeof(int));
    
            var ans1Parameter = ans1 != null ?
                new ObjectParameter("ans1", ans1) :
                new ObjectParameter("ans1", typeof(string));
    
            var ans2Parameter = ans2 != null ?
                new ObjectParameter("ans2", ans2) :
                new ObjectParameter("ans2", typeof(string));
    
            var ans3Parameter = ans3 != null ?
                new ObjectParameter("ans3", ans3) :
                new ObjectParameter("ans3", typeof(string));
    
            var ans4Parameter = ans4 != null ?
                new ObjectParameter("ans4", ans4) :
                new ObjectParameter("ans4", typeof(string));
    
            var ans5Parameter = ans5 != null ?
                new ObjectParameter("ans5", ans5) :
                new ObjectParameter("ans5", typeof(string));
    
            var ans6Parameter = ans6 != null ?
                new ObjectParameter("ans6", ans6) :
                new ObjectParameter("ans6", typeof(string));
    
            var ans7Parameter = ans7 != null ?
                new ObjectParameter("ans7", ans7) :
                new ObjectParameter("ans7", typeof(string));
    
            var ans8Parameter = ans8 != null ?
                new ObjectParameter("ans8", ans8) :
                new ObjectParameter("ans8", typeof(string));
    
            var ans9Parameter = ans9 != null ?
                new ObjectParameter("ans9", ans9) :
                new ObjectParameter("ans9", typeof(string));
    
            var ans10Parameter = ans10 != null ?
                new ObjectParameter("ans10", ans10) :
                new ObjectParameter("ans10", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Student_Answer", exam_NoParameter, std_IDParameter, ans1Parameter, ans2Parameter, ans3Parameter, ans4Parameter, ans5Parameter, ans6Parameter, ans7Parameter, ans8Parameter, ans9Parameter, ans10Parameter);
        }
    
        public virtual int UpdateAnswer(Nullable<int> stID, Nullable<int> questID, Nullable<int> examID, string stAnswer)
        {
            var stIDParameter = stID.HasValue ?
                new ObjectParameter("stID", stID) :
                new ObjectParameter("stID", typeof(int));
    
            var questIDParameter = questID.HasValue ?
                new ObjectParameter("questID", questID) :
                new ObjectParameter("questID", typeof(int));
    
            var examIDParameter = examID.HasValue ?
                new ObjectParameter("examID", examID) :
                new ObjectParameter("examID", typeof(int));
    
            var stAnswerParameter = stAnswer != null ?
                new ObjectParameter("stAnswer", stAnswer) :
                new ObjectParameter("stAnswer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateAnswer", stIDParameter, questIDParameter, examIDParameter, stAnswerParameter);
        }
    
        public virtual ObjectResult<string> UpdateCourse_Ins(Nullable<int> crsID, Nullable<int> insID)
        {
            var crsIDParameter = crsID.HasValue ?
                new ObjectParameter("crsID", crsID) :
                new ObjectParameter("crsID", typeof(int));
    
            var insIDParameter = insID.HasValue ?
                new ObjectParameter("insID", insID) :
                new ObjectParameter("insID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UpdateCourse_Ins", crsIDParameter, insIDParameter);
        }
    
        public virtual ObjectResult<string> UpdateIns_Course(Nullable<int> insId, Nullable<int> courseID)
        {
            var insIdParameter = insId.HasValue ?
                new ObjectParameter("insId", insId) :
                new ObjectParameter("insId", typeof(int));
    
            var courseIDParameter = courseID.HasValue ?
                new ObjectParameter("CourseID", courseID) :
                new ObjectParameter("CourseID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UpdateIns_Course", insIdParameter, courseIDParameter);
        }
    
        public virtual int UpdateStudGrade(Nullable<int> g, Nullable<int> stId, Nullable<int> crsId)
        {
            var gParameter = g.HasValue ?
                new ObjectParameter("G", g) :
                new ObjectParameter("G", typeof(int));
    
            var stIdParameter = stId.HasValue ?
                new ObjectParameter("stId", stId) :
                new ObjectParameter("stId", typeof(int));
    
            var crsIdParameter = crsId.HasValue ?
                new ObjectParameter("crsId", crsId) :
                new ObjectParameter("crsId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateStudGrade", gParameter, stIdParameter, crsIdParameter);
        }
    }
}
