//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sql_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructor
    {
        public int Instructor_ID { get; set; }
        public string Inst_Name { get; set; }
        public string Ins_UserName { get; set; }
        public string Ins_Password { get; set; }
        public string Salary { get; set; }
        public int Dept_ID { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
